# Site
repository: kkostenkov/kkostenkov.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kirill Kostenkov
title: Lead Game Developer
email: kkostenkov@gmail.com
#website: www.kkostenkov.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  kkostenkov
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: kkostenkov
linkedin_username: kkostenkov
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Telegram
  icon: fab fa-telegram
  url: https://t.me/kiparis87

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Kirill and I'm a lead game developer. As well as organizing dev teams I also have experience in C# programming and the Unity game engine. I have worked on a number of projects gaining teamwork and leadership skills.

  My tech expertise lies in <mark>Unity</mark> and <mark>C#</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Helio
        link: heliogames.com
        # link_text: boringcompany.com
        sub_title: Lead developer
        caption: December 2019 - Present
        quote: >
          Development Teamlead as a choice for the prestige class
        description: | # this will include new lines to allow paragraphs
            Conducting code-reviews, interviews, hiring programmers and tech artists, arranging development and tech plans and being responsible for deadlines.
      - layout: left
        title: Nival
        link: nival.com
        sub_title: Senior unity developer
        caption: January 2017 - November 2019
        quote: >
          Leveling up in a real game dev environment.
        description: |
            Made my way from middle to senior C# dev. Supported several existing titles and contributed to couple prototypes that were not released.
      - layout: left
        title: iLocked
        link: ilocked.ru
        sub_title: Unity developer (VR)
        caption: May 2016 - November 2016
        description: |
            Solo developer of multiplayer VR quest with full immersion. Players in VR helmets and suits interact with physical objects in the real world via Oculus Rift, HTC Vive, Perception Neuron (Motion capture suit)

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: St. Petersburg State University of Engineering and Economics
        caption: 2005 - 2010
        sub_title: Human resources specialist
        quote: >
          Most of nowadays IT-folk had little to no idea what they are really going to do after their graduation.
        description: | # this will include new lines to allow paragraphs
          During my time at ENGECON I learned most of my key management skills that helped in my career. 

  - title: Skills
    layout: text
    content: | 
      <mark>Management</mark>, <mark>Unity</mark>, <mark>C#</mark>, <mark>.Net Core</mark>,  <mark>ASP.NET Core</mark>, <mark>Estimating</mark>, <mark>MongoDB</mark>, <mark>Git</mark>, <mark>Mercurial</mark>, <mark>SVN</mark>, <mark>Atlassian Confluence</mark>, <mark>Jira</mark>, <mark>Legacy digging</mark>, <mark>Python</mark>

  - title: Projects
    layout: text
    content: |
      [Some of my projects you could find over here](portfolio)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Open-minded, sociable, with a good sense of humour.
      Alongside my interests in games and software engineering some of my other interests and hobbies are:
      - Tinkering
      - Crossfit
      - Shooting
      - [Geocaching](https://www.geocaching.com/)

      Best of luck  
      ![Fairy-tales cat](/images/cat_1.jpg "Fairy-tales cat")

  - title: Portfolio # Portfolio content only. Ignored in rendering of main.
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Krownguards
        link: https://www.youtube.com/watch?v=iMxsekdAsmI
        link_text: Steam Greenlight trailer
        description: |
          #### Project
          <img src="images/portfolio/krownguards.png" width="25%" align="right"/>    

          - Indie development    
          - Session-based competitive tower defense    
          - Synchronous multiplayer for up to 8 players    
          - Development stopped at Beta.    

          #### My part
          - Solo client-side programming 
          - Integration of assets 
          - Some server tweaks.    

          <img src="images/portfolio/krownguards_gameplay.png" width="50%" height="100%" align="right"/> 

          #### Tech & skills
          <mark>First steps with Unity and C#</mark>   
          <mark>TCP </mark> 
          <mark>JSON</mark>    
          <mark>LZMA</mark>    
          <mark>Python </mark>   
          <mark>Tornado</mark>   
          <mark>Git</mark>   
          <mark>Python</mark>

      - layout: top-middle
        title: Tardis 
        description: |
          #### Project
          <img src="images/portfolio/tardis_vive_controller.png" width="25%" align="right"/>
          - Escape the room live quest    
          - Multiplayer VR game    
          - Released    

          <br clear="all" />

          #### My part

          <img src="images/portfolio/tardis_promo.png" width="25%" align="right"/>

          - App architecture planning
          - All programming work
          - Integration of SDKs and hardware to Unity

          <br clear="all" />

          #### Tech & skills

          <img src="images/portfolio/tardis_mirror.png" width="50%" height="100%" align="right"/> 

          <mark>Unity profiler</mark>   
          <mark>Visual Studio</mark>   
          <mark>Perception Neuron</mark>   
          <mark>HTC Vive</mark> 
          <mark>Oculus Rift</mark>    
          <mark>Leap Motion</mark>    
          <mark>Atlassian Jira</mark>    


      # - layout: top-middle
      #   title: Title
      #   link: some link
      #   link_text: and link tesxt
      #   additional_links:
      #     - title:  sproogen/modern-resume-theme
      #       icon: fab fa-github
      #       url: github.com/sproogen/modern-resume-theme
      #     - title:  Github page for project (eg. sproogen/modern-resume-theme)
      #       icon: fab fa-github
      #       url: Link to project (eg. sproogen.github.io/modern-resume-theme)
      #   quote: >
      #     This is probably one of the greatest apps
      #   description: |
      #     I started this project

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
