# Site
repository: kkostenkov/kkostenkov.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kirill Kostenkov
title: Lead Game Developer
email: kkostenkov@gmail.com
#website: www.kkostenkov.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  kkostenkov
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: kkostenkov
linkedin_username: kkostenkov
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Telegram
  icon: fab fa-telegram
  url: https://t.me/kiparis87

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Kirill and I'm a lead game developer. As well as organizing dev teams I also have experience in C# programming and the Unity game engine. I have worked on a number of projects gaining teamwork and leadership skills.

  My tech expertise lies in <mark>Unity</mark> and <mark>C#</mark>

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Helio
        link: heliogames.com
        # link_text: boringcompany.com
        sub_title: Lead developer
        caption: December 2019 - Present
        quote: >
          Development Teamlead as a choice for the prestige class
        description: | # this will include new lines to allow paragraphs
            Conducting code-reviews, interviews, hiring programmers and tech artists, arranging development and tech plans and being responsible for deadlines.
      - layout: left
        title: Nival
        link: nival.com
        sub_title: Senior unity developer
        caption: January 2017 - November 2019
        quote: >
          Leveling up in a real game dev environment.
        description: |
            Made my way from middle to senior C# dev. Supported several existing titles and contributed to couple prototypes that were not released.
      - layout: left
        title: iLocked
        link: ilocked.ru
        sub_title: Unity developer (VR)
        caption: May 2016 - November 2016
        description: |
            Solo developer of multiplayer VR quest with full immersion. Players in VR helmets and suits interact with physical objects in the real world via Oculus Rift, HTC Vive, Perception Neuron (Motion capture suit)

  - title: Education
    layout: list
    content:
      - layout: left
        title: St. Petersburg State University of Engineering and Economics
        caption: 2005 - 2010
        sub_title: Human resources specialist
        quote: >
          Most of nowadays IT-folk had little to no idea what they are really going to do after their graduation.
        description: |
          During my time at ENGECON I learned most of my key management skills that helped in my career. 

  - title: Skills
    layout: text
    content: | 
      <mark>Management</mark>, <mark>Unity</mark>, <mark>C#</mark>, <mark>.Net Core</mark>,  <mark>ASP.NET Core</mark>, <mark>Estimating</mark>, <mark>MongoDB</mark>, <mark>Git</mark>, <mark>Mercurial</mark>, <mark>SVN</mark>, <mark>Atlassian Confluence</mark>, <mark>Jira</mark>, <mark>Legacy digging</mark>, <mark>Python</mark>

  - title: Projects
    layout: text
    content: |
      [Some of my projects you could find over here](portfolio)

  - title: A Little More About Me
    layout: text
    content: |
      Open-minded, sociable, with a good sense of humour.
      Alongside my interests in games and software engineering some of my other interests and hobbies are:
      - Tinkering
      - Crossfit
      - Shooting
      - [Geocaching](https://www.geocaching.com/)

      Best of luck  
      ![Fairy-tales cat](/images/cat_1.jpg "Fairy-tales cat")

  - title: Portfolio
    layout: list
    content:
      - layout: top-middle
        title: "Mutiny: Pirate Survival RPG"
        additional_links:
          - title:  YouTube
            icon: fab fa-youtube
            url: https://www.youtube.com/watch?v=4wbXPQjcY1w
          - title:  Google Play
            icon: fab fa-google-play
            url: https://play.google.com/store/apps/details?id=com.heliogames.pirates
          - title:  App Store
            icon: fab fa-app-store
            url: https://apps.apple.com/ru/app/mutiny-pirate-survival-rpg/id1490838880
        description: |
          #### Project
          <img src="images/portfolio/mutiny_poster.png" width="33%" align="right"/>
          Survival RPG    
          Pirate crew management    
          Async PvP    
          
          #### My part
          - Lead of programming & techartist teams    
          - Conducting trainee camp programm    
          - Hiring new teammembers    
          - Version planning with responsibility for arranged deadlines    

          #### Tech & skills
          <mark>Tech planning</mark>, <mark>Roadmap composing</mark>, <mark>Hiring & Firing</mark>, <mark>Helping subordinates to build teams</mark>

      - layout: top-middle
        title: PL & FK
        description: |
          #### Project
          <img src="images/portfolio/nda.png" width="15%" align="right"/>

          Standalone strategy-RPG with indirect PvP    
          and    
          Mobile + Standalone adventure-survival

          #### My part

          - Lead of programming team (4 programmers)
          - Architecture planning
          - Task management
          - C# programming
          - Code review
          - Prototype development
          - Communication with art team
          - Cross-platform and cross-project libraries creation

          #### Tech & skills  

          <mark>Team-leading</mark>, <mark>GPU profiling</mark>, <mark>CPU and memory profiling</mark>, <mark>ECS</mark>, <mark>Telepathy</mark>, <mark>Synchronous multiplayer</mark>

      - layout: top-middle
        title: "Prime World: Defenders 2"
        additional_links:
        - title:  Google Play
          icon: fab fa-google-play
          url: https://play.google.com/store/apps/details?id=com.nival.pwdefenders2
        - title:  App Store
          icon: fab fa-app-store
          url: https://apps.apple.com/us/app/defenders-2-tower-defense-ccg/id939529493
        description: |
          #### Project
          <img src="images/portfolio/defenders2_gameplay.png" width="33%" align="right"/>

          - Mobile + Standalone game
          - Tower defense
          - with CCG elements
          - Still in operation

          <br clear="all" />
          <img src="images/portfolio/defenders2_map.png" width="33%" align="right"/>
          #### My part

          - Senior C# developer
          - Port from mobile to Valve’s Steam
          - Implemented new asynchronous PvP mode
          - Added new metagame mechanics
          - Support of existing SDKs         

          #### Tech & skills  

          <mark>Steam</mark>, <mark>ECS</mark>, <mark>Server progress saves</mark>, <mark>NGUI</mark>, <mark>Facebook statistics</mark>    

      - layout: top-middle
        title: "Prime World: Stories"
        description: |
          #### Project
          <img src="images/portfolio/pw_stories.png" width="10%" align="right"/>

          - Mobile + Web game
          - Arcade shoot’em up
          - Rapid development
          - Released
          
          <br clear="all" />
          <img src="images/portfolio/pw_stories_gameplay.png" width="33%" align="right"/>

          #### My part
          - Lua programmer
          - Chief in team of only 2 devs
          - From idea to release in 2 weeks

          #### Tech & skills
          <mark>Defold engine</mark>, <mark>HTML5</mark>, <mark>Lua</mark>, <mark>Sprite animation</mark>

      - layout: top-middle
        title: "King’s Bounty: Legions"
        additional_links:
          - title:  Google Play
            icon: fab fa-google-play
            url: https://play.google.com/store/apps/details?id=com.kranx.kbl
          - title:  App Store
            icon: fab fa-app-store
            url: https://apps.apple.com/ru/app/kings-bounty-legions-rpg/id507975944
          - title:  Steam
            icon: fab fa-steam
            url: https://store.steampowered.com/app/25900/Kings_Bounty_The_Legend/
        description: |
          #### Project
          <img src="images/portfolio/kbl.png" width="33%" align="right"/>
          
          - Mobile + standalone game
          - Turn-Based
          - Synchronous PvP multiplayer
          - Still in operation
          - Lots of operated time-events and activities for players

          <img src="images/portfolio/kbl_battle.png" width="33%" align="right"/>

          #### My part
          - C# programmer
          - Deep legacy code diving
          - Almost reverse engineering of the existing project
          - Social network SDK integration and support
          - Integrated video ads
          - Implemented new game modes

          #### Tech & skills
          <mark>SVN</mark>, <mark>Photon Engine</mark>, <mark>Silverlight</mark>, <mark>AssetBundles</mark>, <mark>Android Studio</mark>, <mark>xCode</mark>, <mark>Facebook SDK</mark>, <mark>Ironsource SDK</mark>

      - layout: top-middle
        title: SS 
        description: |
          #### Project
          <img src="images/portfolio/nda.png" width="15%" align="right"/>

          - Mobile game
          - Battler with narrative campaign
          - Asynchronous multiplayer
          - Development stopped after softlaunch.
          

          #### My part
          - Middle C# programmer
          - Water boy of more experienced Unity devs
          - Improved tools for GMs and operating manager
          - Integrated statistics gathering

          #### Tech & skills
          <mark>Mercurial</mark>, <mark>Unity UI</mark>, <mark>MongoDB</mark>, <mark>ReSharper</mark>, <mark>Programming patterns</mark>, <mark>Predicted random</mark>, <mark>Atlassian Confluence</mark>, <mark>Mobile plugins and SDKs</mark>, <mark>Firebase</mark>, <mark>Teamcity</mark>, <mark>Django</mark>    

      - layout: top-middle
        title: Tardis 
        description: |
          #### Project
          <img src="images/portfolio/tardis_promo.png" width="25%" align="right"/>
          
          - Escape the room live quest    
          - Multiplayer VR game    
          - Released    

          <br clear="all" />
          <img src="images/portfolio/tardis_mirror.png" width="33%" height="100%" align="right"/> 

          #### My part
          - App architecture planning
          - All programming work
          - Integration of SDKs and hardware to Unity

          #### Tech & skills
          <mark>Unity profiler</mark>, <mark>Visual Studio</mark>, <mark>Perception Neuron</mark>, <mark>HTC Vive</mark>, <mark>Oculus Rift</mark>, <mark>Leap Motion</mark>, <mark>Atlassian Jira</mark>    

      - layout: top-middle
        title: Krownguards
        link: https://www.youtube.com/watch?v=iMxsekdAsmI
        link_text: Steam Greenlight trailer
        description: |
          #### Project
          <img src="images/portfolio/krownguards.png" width="25%" align="right"/>    

          - Indie development    
          - Session-based competitive tower defense    
          - Synchronous multiplayer for up to 8 players    
          - Development stopped at Beta.    

          #### My part
          - Solo client-side programming 
          - Integration of assets 
          - Some server tweaks.    

          <br clear="all" />
          <img src="images/portfolio/krownguards_gameplay.png" width="33%" height="100%" align="right"/> 

          #### Tech & skills
          <mark>First steps with Unity and C#</mark>, <mark>TCP</mark>, <mark>JSON</mark>, <mark>LZMA</mark>, <mark>Python</mark>, <mark>Tornado</mark>, <mark>Git</mark>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
