# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kirill Kostenkov
title: Lead Game Developer
email: kkostenkov@gmail.com
#website: www.kkostenkov.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  kkostenkov
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: kkostenkov
linkedin_username: kkostenkov
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Kirill and I'm a lead game developer. As well as organizing dev teams I also have experience in C# programming and Unity game engine. I have worked at a number of projects gaining teamwork and leadership skills.

  My tech expertise lies in <mark>Unity</mark> and <mark>C#</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Helio
        link: heliogames.com
        # link_text: boringcompany.com
        sub_title: Lead developer
        caption: December 2019 - Present
        quote: >
          Development Teamlead as a choise for the prestige class
        description: | # this will include new lines to allow paragraphs
            Conducting code-reviews, interviews, hiring programmers and tech artists, arranging development and tech plans and being responsible for deadlines.
      - layout: left
        title: Nival
        link: nival.com
        sub_title: Senior unity developer
        caption: January 2017 - November 2019
        quote: >
          Leveling up in a real gamedev environment.
        description: |
            Made my way from middle to senior C# dev. Supported several existing titles and put in effort to make couple prototypes that were not released.
      - layout: left
        title: iLocked
        link: ilocked.ru
        sub_title: Unity developer (VR)
        caption: May 2016 - November 2016
        description: |
            Solo developer of multiplayer VR quest with full immersion. Players in VR helments and suits interact with physical objects in real world via Oculus Rift, HTC Vive, Perception Neuron (Motion capture suit)


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: St. Petersburg State University of Engineering and Economics
        caption: 2005 - 2010
        sub_title: Human resources specialist
        quote: >
          Most of nowadays IT-folk had little to no idea what they are really going to do after their graduation.
        description: | # this will include new lines to allow paragraphs
          During my time at ENGECON I learned most of my key management skills that helped in my career. 
          
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome projects
  #       # link: github.com/sproogen
  #       # link_text: Project Website
  #       # additional_links:
  #       #   - title:  sproogen/modern-resume-theme
  #       #     icon: fab fa-github
  #       #     url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       # quote: >
  #       #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Skills
    layout: text
    content: | 
      <mark>Management</mark>, <mark>Unity</mark>, <mark>C#</mark>, <mark>.Net Core</mark>,  <mark>ASP.NET Core</mark>, <mark>Estimating</mark>, <mark>MongoDB</mark>, <mark>Git</mark>, <mark>Mercurial</mark>, <mark>SVN</mark>, <mark>Atlassian Confluence</mark>, <mark>Jira</mark>, <mark>Legacy digging</mark>, <mark>Python</mark>

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Open-minded, sociable, with a good sence of humour.
      Alongside my interests in games and software engineering some of my other interests and hobbies are:
      - Tinkering
      - Crossfit
      - Shooting
      - [Geocaching](https://www.geocaching.com/)

      Best of luck  
      ![Fairy-tales cat](/images/cat_1.jpg "Fairy-tales cat")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
